export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";

export const SORT_PRODUCTS = "SORT_PRODUCTS";
export const UPDATE_SORT = "UPDATE_SORT";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const CLEAR_FILTER = "CLEAR_FILTER";

export const FETCH_SINGLE_PRODUCT_START = "FETCH_SINGLE_PRODUCT_START";
export const FETCH_SINGLE_PRODUCT_SUCCESS = "FETCH_SINGLE_PRODUCT_SUCCESS";
export const FETCH_SINGLE_PRODUCT_FAILED = "FETCH_SINGLE_PRODUCT_FAILED";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ITEM_IN_CART = "REMOVE_ITEM_IN_CART";
export const CLEAR_CART = "CLEAR_CART";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_START = "AUTH_START";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const ORDER_START = "ORDER_START";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAILED = "ORDER_FAILED";

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS";
export const ADD_TO_WISHLIST_FAILED = "ADD_TO_WISHLIST_FAILED";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const REMOVE_FROM_WISHLIST_SUCCESS = "REMOVE_FROM_WISHLIST_SUCCESS";
export const REMOVE_FROM_WISHLIST_FAILED = "REMOVE_FROM_WISHLIST_FAILED";
export const CLEAR_WISHLIST = "CLEAR_WISHLIST";
export const CLEAR_WISHLIST_SUCCESS = "CLEAR_WISHLIST_SUCCESS";
export const CLEAR_WISHLIST_FAILED = "CLEAR_WISHLIST_FAILED";
export const FETCH_ITEM_WISHLIST_START = "FETCH_ITEM_WISHLIST_START";
export const FETCH_ITEM_WISHLIST_SUCCESS = "FETCH_ITEM_WISHLIST_SUCCESS";
export const FETCH_ITEM_WISHLIST_FAILED = "FETCH_ITEM_WISHLIST_FAILED";
